### ISSUE TITLE
.dic version for PocketBook

### ISSUE THREAD

**Issue by user629423** [karlb/wikdict-gen#7]
Hi Karlb, thanks for the great work! Can you please add a version for the PocketBook .dic format?

**Comment by karlb** [comment]
Thanks for the feedback! I'm relying on [pyglossary](https://github.com/ilius/pyglossary/) to export dictionaries to other formats, which does not support PocketBook .dic, yet. If that changes, I can add it to the supported formats. Until then, I will not add support due to lack of time.

If you want to try to convert a dictionary yourself, I would recommend to start with the StarDict exports and use https://github.com/Markismus/PocketBookDic to convert it.
